name: edurise
description: Edurise — educational platform (minimal starter following Clean Architecture + Riverpod)
version: 0.1.0
environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.0
  cupertino_icons: ^1.0.5
  rive: ^0.13.20
  google_fonts: ^5.0.0
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  google_sign_in: ^6.1.0
  image_picker: ^1.2.0
  firebase_storage: ^13.0.2
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  cloud_firestore: ^6.0.2
  http: ^1.1.0
  riverpod_annotation: ^3.0.1
  cached_network_image: ^3.4.1
  video_player: ^2.8.1
  chewie: ^1.7.4
  pod_player: ^0.2.1
  webview_flutter: ^4.4.2
  firebase_database: ^12.0.2
  rxdart: ^0.28.0
  flutter_markdown: ^0.6.18
  url_launcher: ^6.2.4
  loading_animation_widget: ^1.2.0+4
  # speech_to_text: ^6.6.0  # temporarily disabled to unblock Android build (plugin Kotlin compile errors)
  pdf: ^3.10.1
  path_provider: ^2.0.15
  open_filex: ^4.2.0
  flutter_pdfview: ^1.2.3
  share_plus: ^12.0.0
  intl: ^0.19.0
  fpdart: ^1.1.0
  fl_chart: ^1.1.1
  uuid: ^4.5.1
  camera: ^0.11.2
  google_mlkit_text_recognition: ^0.15.0
  printing: ^5.14.2
  image: ^4.5.4
  barcode: ^2.2.8
  flutter_svg: ^2.2.1

dev_dependencies:
  build_runner: ^2.7.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  lint: ^2.0.0
  riverpod_generator: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/files/
    - assets/fonts/
    - assets/icons/
