// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDikrjHPcfm79h3JXR47B68H2ISVXhy9dU',
    appId: '1:514767525071:android:25dda3ad1f4773d68f93ba',
    messagingSenderId: '514767525071',
    projectId: 'edurise-3fec9',
    storageBucket: 'edurise-3fec9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9fe7ujU5jI_w7RF9AKj5axxu84lP6u0c',
    appId: '1:514767525071:ios:9b29bfa2f1ca035c8f93ba',
    messagingSenderId: '514767525071',
    projectId: 'edurise-3fec9',
    storageBucket: 'edurise-3fec9.firebasestorage.app',
    iosClientId:
        '514767525071-2ikage7vhdsv4tst04bmo565asrq4tev.apps.googleusercontent.com',
    iosBundleId: 'com.edurise.edurise',
  );
}
